### new user

Post http://localhost:3000/signup 
Content-Type: application/json

{"firstName": "Jan", 
"lastName":"Green", 
"userName":"jgreen@yahoo.com", 
"password": "123456", 
"confirm": "123456"}



### user login get token

Post http://localhost:3000/login
Content-Type: application/json

{ 
"userName":"jgreen@yahoo.com", 
"password": "123456"
}

### get user messages

Post http://localhost:3000/users/allmessages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpncmVlbkB5YWhvby5jb20iLCJpYXQiOjE3MDczMzQ2ODksImV4cCI6MTcwNzMzNjY4OX0.8Qma-ikOMqrqn5rE-IvRbNgozgA8QJEr-FMRNT7RE5A
Content-Type: application/json

{ 
"userName":"65baeb34b3128250da42b385"

}

### send message

Post http://localhost:3000/users/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpncmVlbkB5YWhvby5jb20iLCJpYXQiOjE3MDczNDQ1OTYsImV4cCI6MTcwNzM0NjU5Nn0.TxJOjSXt14UlSsTtLvfcqjgiikYQS2ZxN3SEvt5lHjs
Content-Type: application/json

{ 
"sentBy":"65baeb34b3128250da42b385", 
"sentTo": "65bc1031d08cc18ebd189239",
"text": "my fith message"
}

### get users

Get http://localhost:3000/users/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpncmVlbkB5YWhvby5jb20iLCJpYXQiOjE3MDcyNjg1ODIsImV4cCI6MTcwNzI3MDU4Mn0.Nff-pZxqnJfwGJhB9wODANV9qHZrB_pEBboTuohNs00
Content-Type: application/json

### delete messages

Delete http://localhost:3000/users/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpncmVlbkB5YWhvby5jb20iLCJpYXQiOjE3MDczMzU5NTksImV4cCI6MTcwNzMzNzk1OX0.-CoiSa22rnzf0tVKlsMkeFM7KurTfMW-Faau8X7pdYQ
Content-Type: application/json




### multipart form request with webkit
POST http://localhost:3000/users/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpncmVlbkB5YWhvby5jb20iLCJpYXQiOjE3MDczNDcxMTcsImV4cCI6MTcwNzM0OTExN30.WOFJVdkJAn5Qdpkw5B4qVMjuC8V_cGiQsT-0yX8zMls
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id"

65baeb34b3128250da42b385
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="./pizza.jpeg"
Content-Type: image/jpeg

< ./pizza.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### delete pic

Delete http://localhost:3000/users/image
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImpncmVlbkB5YWhvby5jb20iLCJpYXQiOjE3MDczNDcxMTcsImV4cCI6MTcwNzM0OTExN30.WOFJVdkJAn5Qdpkw5B4qVMjuC8V_cGiQsT-0yX8zMls
Content-Type: application/json

{ 
"user_id":"65baeb34b3128250da42b385"

}